policy_name: UniVTAC_ACT
protocol: ws
host: 127.0.0.1
port: 19001
bench_name: UniVTAC
task_name: grasp_classify
env_cfg_type: univtac_franka
action_type: joint
device: cuda:0
ckpt_dir: data/xpolicylab/grasp_classify/act_one
camera_names: [cam_head]
tactile_names: [cam_tactile_left, cam_tactile_right]
state_dim: 8
policy_class: ACT
chunk_size: 4
hidden_dim: 64
dim_feedforward: 128
kl_weight: 1.0
temporal_agg: false
backbone: resnet18
position_embedding: sine
lr_vision_backbone: 0.0
lr_tactile_backbone: 0.0
weight_decay: 0.0001
lr: 0.0001
masks: false
tactile_masks: false
dilation: false
tactile_type: full
tactile_backbone: resnet18
tactile_ckpt: null
nheads: 4
enc_layers: 1
dec_layers: 1
pre_norm: false
dropout: 0.1
